title: N훮n훮 Ikehu (N훮n훮: To observe, Ikehu: energy)
theme: jekyll-theme-hacker
description: Visualize Energy http://nanaikehu.meteorapp.com/
github:
  repository_url: https://github.com/nanaikehu/Nana-Ikehu
